### ISSUE TITLE
接続先設定の秘密鍵、バックアップ先のフォームにフォルダを開くボタンを付ける

### ISSUE THREAD

**Issue by rutti-bep** [TakahiroSato/deploy-tool#3]
![2018-06-29 14 33 55](https://user-images.githubusercontent.com/18680028/42074932-88e191f4-7ba9-11e8-91eb-fdfe5d4920db.png)
赤枠の部分につける

**Comment by TakahiroSato** [comment]
ダイアログモジュールを使う
https://electronjs.org/docs/api/dialog
http://nhamada.hatenablog.com/entry/2015/05/24/210639
https://qiita.com/_takwat/items/11dae9f4650767d20c4f
